# Generated by Django 2.0.5 on 2018-05-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(max_length=400),
        ),
    ]
