# Generated by Django 2.0.5 on 2018-05-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180520_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('company', models.TextField()),
                ('link', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
